/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: acd3a981f2871940c08b5ecf7a6c607e)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ENV: "production";
	CREATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV">> {}
}
