/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: df7cf4bf5a70f567b915d82110bf79d4)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ENV: "production";
	PBKDF2_ITERATIONS: "50000";
	SESSION_TTL_SECONDS: "1209600";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "PBKDF2_ITERATIONS" | "SESSION_TTL_SECONDS">> {}
}
